setwd("C:/Users/Wiebke")
library(readxl)
C_DISEASE_TX <- read_excel("Desktop/Doktorarbeit/PV332/data/PV0332_D00127_NODUP.xlsx")
table(C_DISEASE_TX$C_DISEASE_TX_ASTHMA)
summary(C_DISEASE_TX$C_DISEASE_TX_ASTHMA)
table(C_DISEASE_TX$C_DISEASE_TX_ALLERG)
summary(C_DISEASE_TX$C_DISEASE_TX_ALLERG)
table(C_DISEASE_TX$C_DISEASE_TX_NEURODER)
summary(C_DISEASE_TX$C_DISEASE_TX_NEURODER)
table(C_DISEASE_TX$C_DISEASE_TX_PSY)
summary(C_DISEASE_TX$C_DISEASE_TX_PSY)
table(C_DISEASE_TX$C_DISEASE_TX_ADHS)
summary(C_DISEASE_TX$C_DISEASE_TX_ADHS)
table(C_DISEASE_TX$C_DISEASE_TX_DEPRES)
summary(C_DISEASE_TX$C_DISEASE_TX_DEPRES)
CHILD_MED_H <- read_excel("Desktop/Doktorarbeit/PV332/data/PV0332_D00129_NODUP.xlsx")
table(CHILD_MED_H$CHILD_MED_H_ASTHMA)
summary(CHILD_MED_H$CHILD_MED_H_ASTHMA)
table(CHILD_MED_H$CHILD_MED_H_ALLERGIE)
summary(CHILD_MED_H$CHILD_MED_H_ALLERGIE)
table(CHILD_MED_H$CHILD_MED_H_ANTIHIST)
summary(CHILD_MED_H$CHILD_MED_H_ANTIHIST)
table(CHILD_MED_H$CHILD_MED_H_HYPOSENS)
summary(CHILD_MED_H$CHILD_MED_H_HYPOSENS)
table(CHILD_MED_H$CHILD_MED_H_NEUROLEPTIKA)
summary(CHILD_MED_H$CHILD_MED_H_NEUROLEPTIKA)
table(CHILD_MED_H$CHILD_MED_H_ANTIPSYCH)
summary(CHILD_MED_H$CHILD_MED_H_ANTIPSYCH)
table(CHILD_MED_H$CHILD_MED_H_ADHS)
summary(CHILD_MED_H$CHILD_MED_H_ADHS)
SDQ <- read_excel("Desktop/Doktorarbeit/PV332/data/PV0332_D00148_NODUP.xlsx")
table(SDQ$SDQ_PRO_SUM)
summary(SDQ$SDQ_PRO_SUM)
table(SDQ$SDQ_HYP_SUM)
summary(SDQ$SDQ_HYP_SUM)
table(SDQ$SDQ_EMO_SUM)
summary(SDQ$SDQ_EMO_SUM)
table(SDQ$SDQ_VER_SUM)
summary(SDQ$SDQ_VER_SUM)
table(SDQ$SDQ_SOP_SUM)
summary(SDQ$SDQ_SOP_SUM)
table(SDQ$SDQ_GES_SCORE)
summary(SDQ$SDQ_GES_SCORE)
E_SDQ <- read_excel("Desktop/Doktorarbeit/PV332/data/PV0332_D00149_NODUP.xlsx")
summary(E_SDQ$E_SDQ_PRO_SUM)
table(E_SDQ$E_SDQ_PRO_SUM)
summary(E_SDQ$E_SDQ_HYP_SUM)
table(E_SDQ$E_SDQ_HYP_SUM)
summary(E_SDQ$E_SDQ_EMO_SUM)
table(E_SDQ$E_SDQ_EMO_SUM)
summary(E_SDQ$E_SDQ_VER_SUM)
table(E_SDQ$E_SDQ_VER_SUM)
summary(E_SDQ$E_SDQ_SOP_SUM)
table(E_SDQ$E_SDQ_SOP_SUM)
summary(E_SDQ$E_SDQ_GES_SCORE)
table(E_SDQ$E_SDQ_GES_SCORE)
WINKLER <- read_excel("Desktop/Doktorarbeit/PV332/data/PV0332_D00159_NODUP.xlsx")
table(WINKLER$WINKLER_SCORE_M)
summary(WINKLER$WINKLER_SCORE_M)
table(WINKLER$WINKLER_SCORE_V)
summary(WINKLER$WINKLER_SCORE_V)
table(WINKLER$WINKLER_SCORE_FAM)
summary(WINKLER$WINKLER_SCORE_FAM)
Freizeit <- read_excel("Desktop/Doktorarbeit/PV332/data/PV0332_T00159_NODUP.xlsx")
FB_Allergy_Parents <- read_excel("Desktop/Doktorarbeit/PV332/data/PV0332_T00213_NODUP.xlsx")
summary(FB_Allergy_Parents$FB_ALLERGY_BP1_F0010)
table(FB_Allergy_Parents$FB_ALLERGY_BP1_F0010)
table(FB_Allergy_Parents$FB_ALLERGY_BP1_F0011)
summary(FB_Allergy_Parents$FB_ALLERGY_BP1_F0011)
table(FB_Allergy_Parents$FB_ALLERGY_BP1_F0012)
summary(FB_Allergy_Parents$FB_ALLERGY_BP1_F0012)
table(FB_Allergy_Parents$FB_ALLERGY_BP1_F0014)
summary(FB_Allergy_Parents$FB_ALLERGY_BP1_F0014)
table(FB_Allergy_Parents$FB_ALLERGY_BP1_F0028)
summary(FB_Allergy_Parents$FB_ALLERGY_BP1_F0028)
table(FB_Allergy_Parents$FB_ALLERGY_BP1_F0029)
summary(FB_Allergy_Parents$FB_ALLERGY_BP1_F0029)
table(FB_Allergy_Parents$FB_ALLERGY_BP1_F0041)
summary(FB_Allergy_Parents$FB_ALLERGY_BP1_F0041)
table(FB_Allergy_Parents$FB_ALLERGY_BP1_F0043)
summary(FB_Allergy_Parents$FB_ALLERGY_BP1_F0043)
table(FB_Allergy_Parents$FB_ALLERGY_BP1_F0059)
summary(FB_Allergy_Parents$FB_ALLERGY_BP1_F0059)
Allergy_youth <- read_excel("Desktop/Doktorarbeit/PV332/data/PV0332_T00214_NODUP.xlsx")
table(Allergy_youth$S010293_F0012)
summary(Allergy_youth$S010293_F0012)
table(Allergy_youth$S010293_F0026)
summary(Allergy_youth$S010293_F0026)
table(Allergy_youth$S010293_F0039)
summary(Allergy_youth$S010293_F0039)
table(Allergy_youth$S010293_F0041)
summary(Allergy_youth$S010293_F0041)
table(Allergy_youth$S010293_F0057)
summary(Allergy_youth$S010293_F0057)
IgE <- read_excel("Desktop/Doktorarbeit/PV332/data/PV0332_T00499_NODUP.xlsx")
table(IgE$IGE_S_1_NUM_VALUE)
summary(IgE$IGE_S_1_NUM_VALUE)
Ige[IgE$IGE_S_1_NUM_VALUE > 100]

adhs.wenn.asthma <- C_DISEASE_TX[ !is.na( C_DISEASE_TX$C_DISEASE_TX_ASTHMA )  & C_DISEASE_TX$C_DISEASE_TX_ASTHMA == 1, c( "C_DISEASE_TX_SIC", "C_DISEASE_TX_ASTHMA", "C_DISEASE_TX_ADHS")]
